name: voila_app
channels:
  - fastchan
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - pip
  - fastbook
  - fastai
  - voila
  - notebook
  - libarchive 
  - libtiff
  - ipywidgets
  - sentencepiece
  - tqdm
  - traitlets=5.9